[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug_wait = []

[dependencies]
aarch64-cpu = "9.4.0"
tock-registers = { version = "0.8.x", features = ["register_types"] }
